# Generated by Django 5.2.6 on 2025-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Velour",
                        max_length=100,
                        verbose_name="Nombre del sitio",
                    ),
                ),
                (
                    "site_subtitle",
                    models.CharField(
                        blank=True,
                        default="Tienda Online",
                        max_length=200,
                        verbose_name="Subtítulo",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="site/", verbose_name="Logo"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+543834653289", max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Activo?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuraciones del Sitio",
            },
        ),
    ]
